const CONSTANTS = {
  TOTAL_CONTACTS: 8,
  MIN_ZOOM: 1.0,
  MAX_ZOOM: 2.5,
  ZOOM_STEP: 0.2,
  STORAGE_KEY: "kontakt_opened",
  RESUMES: [
    {
      id: "person-1",
      name: "FarLine99",
      x: 50,
      y: 30,
      path: "resumes/person-1/index.html",
      avatar: "resumes/person-1/avatar.png",
      icon: "resumes/person-1/icon.png",
    },
    {
      id: "person-2",
      name: "GUVI",
      x: 64,
      y: 36,
      path: "resumes/person-2/index.html",
      avatar: "resumes/person-2/avatar.jpg",
      icon: "resumes/person-2/icon.png",
    },
    {
      id: "person-3",
      name: "Apehovesrame",
      x: 70,
      y: 50,
      path: "resumes/person-3/index.html",
      avatar: "resumes/person-3/avatar.jpg",
      icon: "resumes/person-3/icon.png",
    },
    {
      id: "person-4",
      name: "K-JUBY",
      x: 34,
      y: 54,
      path: "resumes/person-4/index.html",
      avatar: "resumes/person-4/avatar.jpg",
      icon: "resumes/person-4/icon.png",
    },
  ],
};
