const CONSTANTS = {
  TOTAL_CONTACTS: 9,
  MIN_ZOOM: 1.0,
  MAX_ZOOM: 2.5,
  ZOOM_STEP: 0.2,
  ANIMATION_DURATION: 3000,
  LINE_DRAW_TIME: 1500,
  STORAGE_KEY: "kontakt_opened",
  VISIT_KEY: "kontakt_visited",
  RESUMES: [
    {
      id: "person-1",
      name: "FarLine99",
      x: 52,
      y: 46,
      path: "resumes/person-1/index.html",
      avatar: "resumes/person-1/avatar.png",
      icon: "resumes/person-1/icon.png",
    },
    {
      id: "person-2",
      name: "GUVI",
      x: 59,
      y: 26,
      path: "resumes/person-2/index.html",
      avatar: "resumes/person-2/avatar.jpg",
      icon: "resumes/person-2/icon.png",
    },
    {
      id: "person-3",
      name: "Apehovesrame",
      x: 68,
      y: 41,
      path: "resumes/person-3/index.html",
      avatar: "resumes/person-3/avatar.jpg",
      icon: "resumes/person-3/icon.png",
    },
    {
      id: "person-4",
      name: "K-JUBY",
      x: 66,
      y: 54,
      path: "resumes/person-4/index.html",
      avatar: "resumes/person-4/avatar.jpg",
      icon: "resumes/person-4/icon.png",
    },
    {
      id: "person-5",
      name: "Alesya0711",
      x: 60,
      y: 83,
      path: "resumes/person-5/index.html",
      avatar: "resumes/person-5/avatar.jpg",
      icon: "resumes/person-5/icon.png",
    },
    {
      id: "person-6",
      name: "Ancilot",
      x: 36,
      y: 54,
      path: "resumes/person-6/index.html",
      avatar: "resumes/person-6/avatar.jpg",
      icon: "resumes/person-6/icon.png",
    },
    {
      id: "person-7",
      name: "Werctus",
      x: 23,
      y: 51,
      path: "resumes/person-7/index.html",
      avatar: "resumes/person-7/avatar.jpg",
      icon: "resumes/person-7/icon.png",
    },
    {
      id: "person-8",
      name: "shblkjo",
      x: 32,
      y: 30,
      path: "resumes/person-8/index.html",
      avatar: "resumes/person-8/avatar.jpg",
      icon: "resumes/person-8/icon.png",
    },
  ],
};
